backend:
  name: github
  repo: riccardo2211/mi-sitio
  branch: main
  base_url: https://jolly-chaja-14b7e8.netlify.app/.netlify/functions
  auth_endpoint: auth

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "pages"
    label: "Páginas"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Título"
        name: "title"
        widget: "string"
      - label: "Contenido"
        name: "body"
        widget: "markdown"








