backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Páginas"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Título"
        name: "title"
        widget: "string"
      - label: "Meta título"
        name: "meta_title"
        widget: "string"
      - label: "Meta descripción"
        name: "meta_description"
        widget: "text"
      - label: "Imagen destacada"
        name: "featured_image"
        widget: "image"
      - label: "Contenido"
        name: "body"
        widget: "markdown"











