backend:
  name: github
  repo: camicentro10/jolly-chaja-14b7e8
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "pages"
    label: "Páginas"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Título"
        name: "title"
        widget: "string"
      - label: "Contenido"
        name: "body"
        widget: "markdown"





