backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "pages"
    label: "Páginas"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Título"
        name: "title"
        widget: "string"
      - label: "Contenido"
        name: "body"
        widget: "markdown"









